use_frameworks!

target 'PDFSlideView_Example' do
  pod 'PDFSlideView', :path => '../'

  target 'PDFSlideView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
