use_frameworks!

target 'SlideViewer_Example' do
  pod 'SlideViewer', :path => '../'

  target 'SlideViewer_Tests' do
    inherit! :search_paths

    # pod 'Quick', '~> 1.2.0'
    # pod 'Nimble', '~> 7.0.2'
  end
end
